#!/bin/bash
#Orders
composer transaction submit -c admin@last-mile-delivery-network -d '{"$class":"org.hyperledger.composer.system.AddAsset","resources":[{
  "$class": "delivery.Order",
  "orderId": "OrderAjmer1",
  "id": 1,
  "holder": "resource:delivery.Warehouse#WarehouseGurgaon",
  "pincode": "305001",
  "buyerRegion": "North",
  "buyerState": "Rajasthan",
  "orderNo": "ORD000AJ1",
  "statusId": 2,
  "transporterStatusId":0,
  "orderDateTime": 122343,
  "orderLocationLat": 26.456118,
  "orderLocationLng": 74.6260124,
  "orderLocationAddress": "38/6, Delhi - Jaipur Expy, Mohammed Pur, Khandsha, Sector 37, Gurugram, Haryana 122004",
  "description": "This is a sample order",
  "qrCodeText": "q6",
  "buyerName": "ExxonMobil",
  "buyerAddress": "111, Faiz Manzil, Nathwan Shah, Dargah Sharif, Khadim Mohalla, Ajmer, Rajasthan 305001",
  "shipperName": "Jay Electronics",
  "shipperAddress": "",
  "sellerCity": "Gurugram, Hariyana",
  "buyerCity": "Ajmer",
  "sellerAddress": "Ground Floor & Basement, SCO No. 18, Sector 10A, Khandsa Road, Gurugram, Haryana 122001",
  "sellerLocationLng": 24.5854,
  "sellerLocationLat": 73.7125,
  "shippingService": "Standard",
  "contactNo": "9876543210",
  "currentLocationReached": "North Warehouse"
},
{
  "$class": "delivery.Order",
  "holder": "resource:delivery.Warehouse#WarehouseGurgaon",
   "orderId": "OrderAjmer2",
  "id": 2,
  "pincode": "305001",
  "buyerRegion": "North",
  "buyerState": "Rajasthan",
  "orderNo": "ORD000AJ2",
  "statusId": 2,
  "transporterStatusId":0,
  "orderDateTime": 122343,
  "orderLocationLat": 26.456118,
  "orderLocationLng": 74.6260124,
  "orderLocationAddress": "38/6, Delhi - Jaipur Expy, Mohammed Pur, Khandsha, Sector 37, Gurugram, Haryana 122004",
  "description": "This is a sample order",
  "qrCodeText": "q7",
  "buyerName": "ExxonMobil",
  "buyerAddress": "111, Faiz Manzil, Nathwan Shah, Dargah Sharif, Khadim Mohalla, Ajmer, Rajasthan 305001",
  "shipperName": "Jay Electronics",
  "shipperAddress": "",
  "sellerCity": "Gurugram, Hariyana",
  "buyerCity": "Ajmer",
  "sellerAddress": "Ground Floor & Basement, SCO No. 18, Sector 10A, Khandsa Road, Gurugram, Haryana 122001",
  "sellerLocationLng": 24.5854,
  "sellerLocationLat": 73.7125,
  "shippingService": "Standard",
  "contactNo": "9876543210",
  "currentLocationReached": "North Warehouse"
},
{
  "$class": "delivery.Order",
  "holder": "resource:delivery.Warehouse#WarehouseGurgaon",
  "orderId": "OrderJaipur1",
  "id": 3,
  "pincode": "302002",
  "buyerRegion": "North",
  "buyerState": "Rajasthan",
  "orderNo": "ORD000JP1",
  "statusId": 2,
  "transporterStatusId":0,
  "orderDateTime": 122343,
  "orderLocationLat": 26.456118,
  "orderLocationLng": 74.6260124,
  "orderLocationAddress": "38/6, Delhi - Jaipur Expy, Mohammed Pur, Khandsha, Sector 37, Gurugram, Haryana 122004",
  "description": "This is a sample order",
  "qrCodeText": "q1",
  "buyerName": "CVS Health",
  "buyerAddress": "Sri Krishna Service Station Amer Road Inside Hpcl, Opp Jal Mahal & Man Sagar Lake, Parasrampuri, Jaipur, Rajasthan 302002",
  "shipperName": "Jay Electronics",
  "shipperAddress": "",
  "sellerCity": "Gurugram, Hariyana",
  "buyerCity": "Ajmer",
  "sellerAddress": "Ground Floor & Basement, SCO No. 18, Sector 10A, Khandsa Road, Gurugram, Haryana 122001",
  "sellerLocationLng": 24.5854,
  "sellerLocationLat": 73.7125,
  "shippingService": "Standard",
  "contactNo": "9876543210",
  "currentLocationReached": "North Warehouse"
},
{
  "$class": "delivery.Order",
  "holder": "resource:delivery.Warehouse#WarehouseGurgaon",
  "orderId": "OrderJaipur2",
  "id": 4,
  "pincode": "302002",
  "buyerRegion": "North",
  "buyerState": "Rajasthan",
  "orderNo": "ORD000JP2",
  "statusId": 2,
  "transporterStatusId":0,
  "orderDateTime": 122343,
  "orderLocationLat": 26.456118,
  "orderLocationLng": 74.6260124,
  "orderLocationAddress": "38/6, Delhi - Jaipur Expy, Mohammed Pur, Khandsha, Sector 37, Gurugram, Haryana 122004",
  "description": "This is a sample order",
  "qrCodeText": "q2",
  "buyerName": "CVS Health",
  "buyerAddress": "Sri Krishna Service Station Amer Road Inside Hpcl, Opp Jal Mahal & Man Sagar Lake, Parasrampuri, Jaipur, Rajasthan 302002",
  "shipperName": "Jay Electronics",
  "shipperAddress": "",
  "sellerCity": "Gurugram, Hariyana",
  "buyerCity": "Ajmer",
  "sellerAddress": "Ground Floor & Basement, SCO No. 18, Sector 10A, Khandsa Road, Gurugram, Haryana 122001",
  "sellerLocationLng": 24.5854,
  "sellerLocationLat": 73.7125,
  "shippingService": "Standard",
  "contactNo": "9876543210",
  "currentLocationReached": "North Warehouse"
},
{
  "$class": "delivery.Order",
  "holder": "resource:delivery.Warehouse#WarehouseGurgaon",
  "orderId": "OrderJaipur3",
  "id": 5,
  "pincode": "302002",
  "buyerRegion": "North",
  "buyerState": "Rajasthan",
  "orderNo": "ORD000JP3",
  "statusId": 2,
  "transporterStatusId":0,
  "orderDateTime": 122343,
  "orderLocationLat": 26.456118,
  "orderLocationLng": 74.6260124,
  "orderLocationAddress": "38/6, Delhi - Jaipur Expy, Mohammed Pur, Khandsha, Sector 37, Gurugram, Haryana 122004",
  "description": "This is a sample order",
  "qrCodeText": "q3",
  "buyerName": "CVS Health",
  "buyerAddress": "Sri Krishna Service Station Amer Road Inside Hpcl, Opp Jal Mahal & Man Sagar Lake, Parasrampuri, Jaipur, Rajasthan 302002",
  "shipperName": "Jay Electronics",
  "shipperAddress": "",
  "sellerCity": "Gurugram, Hariyana",
  "buyerCity": "Ajmer",
  "sellerAddress": "Ground Floor & Basement, SCO No. 18, Sector 10A, Khandsa Road, Gurugram, Haryana 122001",
  "sellerLocationLng": 24.5854,
  "sellerLocationLat": 73.7125,
  "shippingService": "Standard",
  "contactNo": "9876543210",
  "currentLocationReached": "North Warehouse"
}],"targetRegistry":"resource:org.hyperledger.composer.system.AssetRegistry#delivery.Order"}'

